### PR TITLE
New orange theme

### PR DESCRIPTION
**Pull request by david-poindexter**
New orange theme.  Some style additions/changes were made in this theme that the other themes could probably benefit from as well.

### CODE REVIEW

**Comment by david-poindexter** [comment]
Any thoughts on this yet @dnnconsulting?

**Comment by dnnconsulting** [comment]
Hi David,
Although the change by adding another 3 colors to the color scheme is understandable, I fear that it might make the theme a bit to complicated when it comes to a novice user. The skin was set up in a way that it fitted with the Kuler color schemes (standard 5 colors) to make it easier for uses to choose a color scheme that fits with there liking.

On the other hand it might be beneficial to add a color change in the themes for the main background and font colors. This is easily done and will try to change this before the next release of the theme.

Again, thanks for you support and contribution,
Geoff.

**Comment by david-poindexter** [comment]
I totally understand the purpose of Kuler.  However, the idea that one can create an effectively designed theme with only those 5 colors is a myth.  At minimum you have to add a close-to-white color and a close-to-black color.  There are so many color uses when it comes to DNN (especially if you include all the built-in admin controls, etc.).  So the idea in my opinion should be to use the 5 colors from the selected Kuler theme as the "primary" theme colors.  Then segregate the other colors necessary for fonts, background, etc.  If you would like for me to take another pass at this, I will.  I am just not sure how soon I can do it due to my heavy workload right now.

**Comment by david-poindexter** [comment]
@dnnconsulting any more thoughts on this?  It has been nearly 6 months now since this PR was made.  I believe others will like this theme if it is made available.

**Pull request merged**
